plugins:
  - "jekyll-remote-theme"
  - "jekyll-feed"
  - "jekyll-seo-tag"
remote_theme: "jekyll/minima@6b9b78d"
minima:
  social_links:
    - platform: github
      user_url: "https://github.com/jekyll/minima"
